//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_shipping_address
    {
        public int int_id { get; set; }
        public Nullable<int> int_user_id { get; set; }
        public Nullable<int> int_city_id { get; set; }
        public Nullable<int> int_state_id { get; set; }
        public string v_pin { get; set; }
        public string v_address { get; set; }
        public string v_mobile_no { get; set; }
        public Nullable<bool> b_IsActive { get; set; }
        public Nullable<System.DateTime> dt_created_on { get; set; }
    }
}
