//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_credit_debit_history
    {
        public int int_id { get; set; }
        public Nullable<int> int_UserId { get; set; }
        public Nullable<double> fl_funds_added { get; set; }
        public Nullable<double> fl_funds_debited { get; set; }
        public Nullable<int> int_credit_for_id { get; set; }
        public Nullable<double> fl_updated_funds { get; set; }
        public Nullable<int> int_credit_type_id { get; set; }
        public Nullable<int> int_payment_type_id { get; set; }
        public Nullable<bool> b_IsActive { get; set; }
        public Nullable<System.DateTime> dt_created_on { get; set; }
    }
}
