//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order_product
    {
        public int int_Id { get; set; }
        public Nullable<int> int_order_id { get; set; }
        public Nullable<int> int_product_id { get; set; }
        public Nullable<double> fl_weight { get; set; }
        public Nullable<double> fl_selling_price { get; set; }
        public Nullable<int> int_color_id { get; set; }
        public Nullable<int> int_quantity { get; set; }
        public Nullable<double> fl_rate { get; set; }
        public Nullable<double> fl_CGST { get; set; }
        public Nullable<double> fl_IGST { get; set; }
        public Nullable<double> fl_SGST { get; set; }
        public Nullable<double> fl_UGST { get; set; }
        public Nullable<double> fl_CGSTPercent { get; set; }
        public Nullable<double> fl_SGSTPercent { get; set; }
        public Nullable<double> fl_UGSTPercent { get; set; }
        public Nullable<double> fl_IGSTPercent { get; set; }
        public Nullable<bool> b_is_modify_product { get; set; }
        public Nullable<System.DateTime> dt_inserted_on { get; set; }
    }
}
