//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Products
    {
        public int int_id { get; set; }
        public string v_code { get; set; }
        public string v_name { get; set; }
        public Nullable<double> fl_price { get; set; }
        public Nullable<double> fl_weight { get; set; }
        public string v_description_info { get; set; }
        public string v_image { get; set; }
        public Nullable<int> int_mpq { get; set; }
        public Nullable<int> int_packs { get; set; }
        public Nullable<int> int_quantity { get; set; }
        public Nullable<double> fl_length { get; set; }
        public Nullable<double> fl_breadth { get; set; }
        public Nullable<double> fl_height { get; set; }
        public string v_hs_code { get; set; }
        public string v_product_video_name { get; set; }
        public Nullable<double> fl_GST { get; set; }
        public Nullable<double> fl_QtyDiscount { get; set; }
        public Nullable<int> int_CategoryId { get; set; }
        public Nullable<int> int_BrandsId { get; set; }
        public Nullable<System.DateTime> dt_created_on { get; set; }
        public Nullable<System.DateTime> dt_modified_on { get; set; }
        public Nullable<bool> b_IsActive { get; set; }
    }
}
