//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_category
    {
        public int int_id { get; set; }
        public string v_category { get; set; }
        public Nullable<bool> b_IsActive { get; set; }
        public Nullable<System.DateTime> dt_inserted_on { get; set; }
    }
}
