//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OTP
    {
        public int int_id { get; set; }
        public Nullable<int> int_moduleType_id { get; set; }
        public Nullable<int> int_user_id { get; set; }
        public Nullable<int> int_OTP { get; set; }
        public Nullable<System.DateTime> dt_OTP_created { get; set; }
        public Nullable<System.DateTime> dt_login_time { get; set; }
        public Nullable<System.DateTime> dt_logout_time { get; set; }
        public string v_device_id { get; set; }
        public string v_device_token { get; set; }
        public string v_device_mode { get; set; }
        public Nullable<System.DateTime> dt_created_on { get; set; }
    }
}
