//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_appointment
    {
        public int int_id { get; set; }
        public string v_appointment { get; set; }
        public Nullable<int> int_emp_Id { get; set; }
        public Nullable<int> int_status { get; set; }
        public Nullable<System.DateTime> dt_created_dt { get; set; }
    }
}
