//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_States
    {
        public int int_Id { get; set; }
        public string v_State { get; set; }
        public Nullable<int> int_CountryId { get; set; }
        public Nullable<bool> b_IsActive { get; set; }
        public Nullable<bool> b_IsUnionTerritories { get; set; }
        public Nullable<System.DateTime> dt_Created_On { get; set; }
    }
}
